name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Linter
        run: ./gradlew lint

      - name: Kotlin sintax
        run: ./gradlew ktlintCheck

      - name: Static code analysis
        run: ./gradlew detekt

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Generate coverage report
        run: ./gradlew koverXmlReport

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/kover/project-xml/report.xml
          flags: unittesting
