name: Merge pull request

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate coverage report
        run: ./gradlew koverXmlReport

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          override_branch: main
          files: app/build/reports/kover/project-xml/report.xml
