name: Publish a release
on:
  push:
    tags:
      - '**' # example: v0.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test action
        run: echo "hello world"
